### ISSUE TITLE
something removes hddtemp package

### ISSUE THREAD

**Issue by promeneur** [guzu/hddtemp#23]
openSUSE Tumbleweed

Since 2022-08-13 something removes hddtemp package.

I reinstall hddtemp then next day I check that hddtemp is removed.

It seems that updating the OS removes hddtemp. The OS is updated each day.

**Comment by vitlav** [comment]
It is not the hddtemp issue. You can you system logs of your OS to check for the reason of the deleting.

**Comment by promeneur** [comment]
It seems that hddtemp is obsolete. I don't use it anymore.
I use now the kernel module drivetemp. This one is included in the kernel since kernel 5.6.

Thanks
